@startuml
skinparam defaultTextAlignment center

' Icons from https://github.com/plantuml/plantuml-stdlib
!include <tupadr3/common>
!include <tupadr3/font-awesome-5/windows.puml>
!include <tupadr3/font-awesome-5/docker.puml>
!include <tupadr3/font-awesome-5/jenkins.puml>

package  "Infrastructure" as i {
  FA5_DOCKER(dc, Docker Compose)

  FA5_WINDOWS(idw, Windows) {
    FA5_DOCKER(wdd, Docker Desktop) {
      FA5_JENKINS(jk, Jenkins)
    }
  }

  dc ..down.> wdd
}

@enduml